cache:
  directories:
  - node_modules
language: node_js
node_js:
  7
branches:
  only:
  - master
script:
- yarn install
- yarn build # build project
install:
  yarn global add -g firebase-tools
after_success:
- firebase use --token ${FIREBASE_TOKEN}
- firebase use --add ${PROJECT_ID}
- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"
